name: flutter_app2
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.2.1
  intl: ^0.15.8
  json_annotation: ^2.0.0
  http: ^0.12.0+2
  firebase_database: 1.0.3
  firebase_core: ^0.2.5
  firebase_analytics: ^1.0.4
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  flutter_cupertino_data_picker: ^0.8.6
  charts_flutter: ^0.8.1
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/piece/